# Generated by Django 3.0.6 on 2020-05-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_author', models.CharField(max_length=300)),
                ('post_grade', models.CharField(choices=[('', 'Select your grade...'), ('Grade 5 Red', 'Grade 5 Red'), ('Grade 5 Blue', 'Grade 5 Blue'), ('Grade 5 White', 'Grade 5 White')], max_length=30)),
                ('post_email', models.EmailField(max_length=500)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_title', models.CharField(max_length=100)),
                ('post_text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Post')),
            ],
        ),
    ]
